name: Deploy Static Site

# 触发条件
on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当创建 pull request 到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate config file
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          echo "const API_KEY = '${DEEPSEEK_API_KEY}';" > config.js
          echo "API Key 已注入 config.js"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./